name: "My Repos"
description: "Repost to profile"

inputs:
  url:
    description: "GitHub GraphQL URL"
    required: true
  token:
    description: "GitHub Personal Access Token"
    required: true
  login:
    description: "GitHub Username"
    required: true
    default: SubZtep

outputs:
  table:
    description: "Projects markdown table"

runs:
  using: "node12"
  main: "index.js"
