name: "My Repos"
description: "Repost to profile"

inputs:
  token:
    description: "GitHub Personal Access Token"
    required: true

outputs:
  table:
    description: "Project list in markdown table"

runs:
  using: "node12"
  main: "index.js"
